version: "3.8"
services:
  db:
    image: postgres:12-alpine
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  web:
    image: football-app
    ports:
    - target: 5000
      published: 5000
    environment:
      DATABASE_URI: postgres://postgres:password@db
      FLASK_APP: app