version: "3.8"
services:
  db:
    image: postgres:12-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  web:
    build:
      context: .
    ports:
    - target: 5000
      published: 5000
    environment:
      DATABASE_URI: postgres://postgres:password@db
      FLASK_APP: app
volumes:
  db_data:
