"""empty message

Revision ID: 804e1445e461
Revises: 899edaefd46e
Create Date: 2021-01-23 01:27:08.499417

"""
from alembic import op
import sqlalchemy as sa
from app.models.password import Password


# revision identifiers, used by Alembic.
revision = '804e1445e461'
down_revision = '899edaefd46e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', Password(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
