"""empty message

Revision ID: 899edaefd46e
Revises: 18d608af4c26
Create Date: 2020-12-02 18:50:02.100279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899edaefd46e'
down_revision = '18d608af4c26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('average_projection', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'average_projection')
    # ### end Alembic commands ###
