"""empty message

Revision ID: b8d95d30550b
Revises: 804e1445e461
Create Date: 2021-02-19 04:24:05.487656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8d95d30550b'
down_revision = '804e1445e461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('player', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projection', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('projection', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'time_updated')
    op.drop_column('user', 'time_created')
    op.drop_column('projection', 'time_updated')
    op.drop_column('projection', 'time_created')
    op.drop_column('player', 'time_updated')
    op.drop_column('player', 'time_created')
    # ### end Alembic commands ###
